github: [thotsecure]
open_collective: thotsecure
liberapay: thotsecure
custom:
  - "https://thotsecure.dev/support"
  - "bitcoin:33cDzgvVe7m9P4X58pW3rsMKuxrRXFmPBR"
  - "solana:95s8JxNzLbre9nopbdxakkc4dtNCzkzA2JUTDFQnM7Hi"
